name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.0

      - name: Gradle Build
        run: ./gradlew build
      
      - name: Gradle Test
        run: ./gradlew test
